---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: must-have-odf-placement
  namespace: policies
placementRef:
  name: must-have-odf-placement
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: must-have-odf
    apiGroup: policy.open-cluster-management.io
    kind: Policy
