apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: install-openshift-serverless
policyDefaults:
  namespace: policies
  placement:
    placementRulePath: ./managed-clusters-placementrule.yaml
  remediationAction: enforce
policies:
  - name: install-openshift-serverless
    manifests:
      - path: ./openshift-serverless-subscription.yaml